import os
import datetime
import re
import subprocess
import sys

from datetime import datetime, timezone
JSDOC_CONFIG = os.path.join(os.getcwd(), "jsdoc.json")
DOCS_DIR = os.path.join(os.getcwd(), "html")

print("🚀 Generating JSDoc...")

try:
    subprocess.run(
        ["pnpm", "exec", "jsdoc", "-c", JSDOC_CONFIG],
        check=True
    )
except subprocess.CalledProcessError as e:
    print("❌ Error generating JSDoc:", e)
    sys.exit(1)

print("🕒 Updating footer timestamps to UTC...")

utc_now = datetime.now(timezone.utc)
utc_str = utc_now.strftime("%Y-%m-%d")

pattern = re.compile(
    r"(Documentation generated by\s*<.*?>.*?</a>\s*on\s*)( .*? )(\s*using the\s*<a.*?>.*?</a>\s*theme\.)",
    re.IGNORECASE | re.DOTALL
)

for root, dirs, files in os.walk(DOCS_DIR):
    for file in files:
        if file.endswith(".html"):
            path = os.path.join(root, file)
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            if pattern.search(content):
                # Replace only the date/time part with YYYY-MM-DD
                content_new = pattern.sub(rf"\1 {utc_str} \3", content)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content_new)