import os
import datetime
import re
import subprocess
import sys

from datetime import datetime, timezone
JSDOC_CONFIG = os.path.join(os.getcwd(), "jsdoc.json")
DOCS_DIR = os.path.join(os.getcwd(), "html")

print("🚀 Generating JSDoc...")

try:
    subprocess.run(
        ["pnpm", "exec", "jsdoc", "-c", JSDOC_CONFIG],
        check=True
    )
except subprocess.CalledProcessError as e:
    print("❌ Error generating JSDoc:", e)
    sys.exit(1)

print("🕒 Updating footer timestamps to UTC...")

utc_now = datetime.now(timezone.utc)
utc_str = utc_now.strftime("%a %b %d %Y %H:%M:%S (UTC)")

pattern = re.compile(
    r"(Generated by\s*<.*?>\s*JSDoc .*?</a>\s*on\s*)(.*?)(\s*using the .* theme\.)",
    re.IGNORECASE
)

for root, dirs, files in os.walk(DOCS_DIR):
    for file in files:
        if file.endswith(".html"):
            path = os.path.join(root, file)
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            
            match = pattern.search(content)
            if match:
                content_new = pattern.sub(r"\1" + utc_str + r"\3", content)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content_new)
